"""Crear tablas iniciales

Revision ID: 431863b5c6a2
Revises: 
Create Date: 2025-05-29 12:30:58.615468

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '431863b5c6a2'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Reemplaza la línea op.add_column existente para 'refresh_interval_minutes' con esto:

    # 1. Añade la columna, permitiendo temporalmente valores NULL
    op.add_column('integration_configs', sa.Column('refresh_interval_minutes', sa.Integer(), nullable=True))

    # 2. Actualiza las filas existentes: Asigna un valor por defecto (ej. 60) a las filas donde la columna es NULL
    op.execute("UPDATE integration_configs SET refresh_interval_minutes = 60 WHERE refresh_interval_minutes IS NULL")

    # 3. Altera la columna para que sea NOT NULL y establece un server_default para futuras inserciones
    op.alter_column('integration_configs', 'refresh_interval_minutes',
                existing_type=sa.Integer(),
                nullable=False,
                existing_nullable=True, # Importante para indicar que antes era nullable
                server_default='60'     # Esto asegura que nuevas inserciones también tengan un valor por defecto en la DB
    )

    # ### end Alembic commands ###



def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('integration_configs', 'refresh_interval_minutes')
    # ### end Alembic commands ###
